namespace _1002_backend.Models;
public class Question
{
    public int Id { get; set; }
    public string Code { get; set; } = string.Empty;
    public string Text { get; set; } = string.Empty;
    public int SectionId { get; set; }
    public int QuestionTypeId { get; set; }
}

/* Question CODEs
SLEEP_WAKEUP_TIME 
SLEEP_BEDTIME
SLEEP_QUALITY
LD_LUCIDITY_ACHIEVED
LD_ATTEMPT_DESCRIPTION
LD_DREAMS_RECALLED
LD_RECALL_QUALITY
MENTAL_STRESS_LEVEL
MENTAL_MIND_WANDERING
MENTAL_LD_ATTITUDE
MENTAL_STRONG_EMOTIONS
MENTAL_STATE_DESCRIPTION
ENV_SCREEN_TIME
ENV_SCREEN_CUTOFF_TIME
ENV_NAP_TAKEN
ENV_NAP_DURATION
ENV_NAP_TIME
ENV_PORN_EXPOSURE
ENV_PORN_INTENSITY
ENV_PORN_TIME
ENV_SEXUAL_ACTIVITY
ENV_SEXUAL_ACTIVITY_INTENSITY
ENV_SEXUAL_ACTIVITY_TIME
PHYS_EXERCISE_TAKEN
PHYS_EXERCISE_INTENSITY
PHYS_EXERCISE_TIME
PHYS_DISCOMFORT_PRESENT
PHYS_DISCOMFORT_INTENSITY
PHYS_DISCOMFORT_DESCRIPTION
PHYS_OVERALL_HEALTH
DIET_CAFFEINE_INTAKE
DIET_CAFFEINE_AMOUNT
DIET_CAFFEINE_TIME
DIET_ALCOHOL_INTAKE
DIET_ALCOHOL_AMOUNT
DIET_ALCOHOL_TIME
DIET_WATER_AMOUNT
DIET_SUPPLEMENTS_DESCRIPTION
*/